<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Vaguei.Application\Vaguei.Application.csproj" />
    <ProjectReference Include="..\Vaguei.Collectors\Vaguei.Collectors.csproj" />
    <ProjectReference Include="..\Vaguei.Domain\Vaguei.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="..\Vaguei.Desktop\Assets\logo-dark-56.png" Link="Assets\logo-dark-56.png" />
    <AvaloniaResource Include="..\Vaguei.Desktop\Assets\logo-light-56.png" Link="Assets\logo-light-56.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
</Project>
